local M = {}

---@param colors table
---@param config? table
function M.setup(colors, config)
    config = config or require("zen").config
    local theme = colors.theme

    return {
        -- Gitsigns
        GitSignsAdd = { fg = theme.vcs.added, bg = theme.ui.none },
        GitSignsChange = { fg = theme.vcs.changed, bg = theme.ui.none },
        GitSignsDelete = { fg = theme.vcs.removed, bg = theme.ui.none },
        GitSignsChangedelete = { fg = theme.vcs.removed, bg = theme.ui.none },
        GitSignsTopdelete = { fg = theme.vcs.removed, bg = theme.ui.none },

        -- Neogit
        NeogitDiffContextHighlight = { bg = theme.diff.change },
        NeogitHunkHeader = { fg = theme.syn.fun },
        NeogitHunkHeaderHighlight = { fg = theme.syn.constant, bg = theme.diff.change },
        NeogitDiffAddHighlight = { bg = theme.diff.add },
        NeogitDiffDeleteHighlight = { bg = theme.diff.delete },

        -- TreeSitter Context
        TreesitterContext = { link = "Folded" },
        TreesitterContextLineNumber = { fg = theme.ui.special, bg = theme.ui.none },

        -- Telescope
        TelescopeBorder = { fg = theme.ui.float.fg_border, bg = config.transparent and theme.ui.none or theme.ui.bg },
        TelescopeTitle = { fg = theme.ui.special },
        TelescopeSelection = { link = "CursorLine" },
        TelescopeSelectionCaret = { link = "CursorLineNr" },
        TelescopeResultsClass = { link = "Structure" },
        TelescopeResultsStruct = { link = "Structure" },
        TelescopeResultsField = { link = "@field" },
        TelescopeResultsMethod = { link = "Function" },
        TelescopeResultsVariable = { link = "@variable" },

        -- NvimTree
        NvimTreeNormal = { link = "Normal" },
        NvimTreeNormalNC = { link = "NvimTreeNormal" },
        NvimTreeRootFolder = { fg = theme.syn.identifier },
        NvimTreeGitDirty = { fg = theme.vcs.changed },
        NvimTreeGitNew = { fg = theme.vcs.added },
        NvimTreeGitDeleted = { fg = theme.vcs.removed },
        NvimTreeGitStaged = { fg = theme.vcs.added },
        NvimTreeSpecialFile = { fg = theme.syn.special1 },
        NvimTreeImageFile = { fg = theme.syn.special2 },
        NvimTreeSymlink = { link = "Type" },
        NvimTreeFolderName = { link = "Directory" },
        NvimTreeExecFile = { fg = theme.syn.string },
        NvimTreeOpenedFile = { fg = theme.syn.special1, italic = true },
        NvimTreeWinSeparator = { link = "WinSeparator" },

        -- NeoTree
        NeoTreeNormal = { link = "Normal" },
        NeoTreeNormalNC = { link = "Normal" },
        NeoTreeRootName = { fg = theme.syn.identifier },
        NeoTreeModified = { link = "String" },
        NeoTreeTitleBar = { link = "Title" },
        NeoTreeDimText = { fg = theme.ui.fg_dim },
        NeoTreeGitModified = { fg = theme.vcs.changed },
        NeoTreeGitAdded = { fg = theme.vcs.added },
        NeoTreeGitDeleted = { fg = theme.vcs.removed },
        NeoTreeGitStaged = { fg = theme.vcs.added },
        NeoTreeGitConflict = { fg = theme.diag.error },
        NeoTreeIndentMarker = { link = "NonText" },

        -- Notify
        NotifyBackground = { bg = config.transparent and theme.ui.none or theme.ui.bg },
        NotifyERRORBorder = { link = "DiagnosticError" },
        NotifyWARNBorder = { link = "DiagnosticWarn" },
        NotifyINFOBorder = { link = "DiagnosticInfo" },
        NotifyHINTBorder = { link = "DiagnosticHint" },
        NotifyDEBUGBorder = { link = "Debug" },
        NotifyTRACEBorder = { link = "Comment" },
        NotifyERRORIcon = { link = "DiagnosticError" },
        NotifyWARNIcon = { link = "DiagnosticWarn" },
        NotifyINFOIcon = { link = "DiagnosticInfo" },
        NotifyHINTIcon = { link = "DiagnosticHint" },
        NotifyDEBUGIcon = { link = "Debug" },
        NotifyTRACEIcon = { link = "Comment" },
        NotifyERRORTitle = { link = "DiagnosticError" },
        NotifyWARNTitle = { link = "DiagnosticWarn" },
        NotifyINFOTitle = { link = "DiagnosticInfo" },
        NotifyHINTTitle = { link = "DiagnosticHint" },
        NotifyDEBUGTitle = { link = "Debug" },
        NotifyTRACETitle = { link = "Comment" },

        -- nvim-cmp
        CmpDocumentation = { link = "NormalFloat" },
        CmpDocumentationBorder = { link = "FloatBorder" },
        CmpCompletion = { link = "Pmenu" },
        CmpCompletionSel = { link = "PmenuSel" },
        CmpCompletionBorder = { fg = theme.ui.bg_search, bg = theme.ui.pmenu.bg },
        CmpCompletionThumb = { link = "PmenuThumb" },
        CmpCompletionSbar = { link = "PmenuSbar" },
        CmpItemAbbr = { fg = theme.ui.pmenu.fg },
        CmpItemAbbrDeprecated = { fg = theme.syn.comment, strikethrough = true },
        CmpItemAbbrMatch = { fg = theme.syn.fun },
        CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
        CmpItemKindDefault = { fg = theme.ui.fg_dim },
        CmpItemMenu = { fg = theme.ui.fg_dim },
        CmpGhostText = { fg = theme.syn.comment },

        CmpItemKindText = { fg = theme.ui.fg },
        CmpItemKindMethod = { link = "@function.method" },
        CmpItemKindFunction = { link = "Function" },
        CmpItemKindConstructor = { link = "@constructor" },
        CmpItemKindField = { link = "@variable.member" },
        CmpItemKindVariable = { fg = theme.ui.fg_dim },
        CmpItemKindClass = { link = "Type" },
        CmpItemKindInterface = { link = "Type" },
        CmpItemKindModule = { link = "@module" },
        CmpItemKindProperty = { link = "@property" },
        CmpItemKindUnit = { link = "Number" },
        CmpItemKindValue = { link = "String" },
        CmpItemKindEnum = { link = "Type" },
        CmpItemKindKeyword = { link = "Keyword" },
        CmpItemKindSnippet = { link = "Special" },
        CmpItemKindColor = { link = "Special" },
        CmpItemKindFile = { link = "Directory" },
        CmpItemKindReference = { link = "Special" },
        CmpItemKindFolder = { link = "Directory" },
        CmpItemKindEnumMember = { link = "Constant" },
        CmpItemKindConstant = { link = "Constant" },
        CmpItemKindStruct = { link = "Type" },
        CmpItemKindEvent = { link = "Type" },
        CmpItemKindOperator = { link = "Operator" },
        CmpItemKindTypeParameter = { link = "Type" },
        CmpItemKindCopilot = { link = "String" },

        -- blink.cmp
        BlinkCmpMenu = { link = "Pmenu" },
        BlinkCmpMenuSelection = { link = "PmenuSel" },
        BlinkCmpMenuBorder = { fg = theme.ui.bg_search, bg = config.transparent and theme.ui.none or theme.ui.pmenu.bg },
        BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
        BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
        BlinkCmpLabel = { fg = theme.ui.pmenu.fg },
        BlinkCmpLabelMatch = { fg = theme.syn.fun },
        BlinkCmpLabelDetails = { fg = theme.syn.comment },
        BlinkCmpLabelDeprecated = { fg = theme.syn.comment, strikethrough = true },
        BlinkCmpGhostText = { fg = theme.syn.comment },
        BlinkCmpDoc = { link = "NormalFloat" },
        BlinkCmpDocBorder = { link = "FloatBorder" },
        BlinkCmpDocCursorLine = { link = "Visual" },
        BlinkCmpSignatureHelp = { link = "NormalFloat" },
        BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
        BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },

        BlinkCmpKind = { fg = theme.ui.fg_dim },
        BlinkCmpKindText = { fg = theme.ui.fg },
        BlinkCmpKindMethod = { link = "@function.method" },
        BlinkCmpKindFunction = { link = "Function" },
        BlinkCmpKindConstructor = { link = "@constructor" },
        BlinkCmpKindField = { link = "@variable.member" },
        BlinkCmpKindVariable = { fg = theme.ui.fg_dim },
        BlinkCmpKindClass = { link = "Type" },
        BlinkCmpKindInterface = { link = "Type" },
        BlinkCmpKindModule = { link = "@module" },
        BlinkCmpKindProperty = { link = "@property" },
        BlinkCmpKindUnit = { link = "Number" },
        BlinkCmpKindValue = { link = "String" },
        BlinkCmpKindEnum = { link = "Type" },
        BlinkCmpKindKeyword = { link = "Keyword" },
        BlinkCmpKindSnippet = { link = "Special" },
        BlinkCmpKindColor = { link = "Special" },
        BlinkCmpKindFile = { link = "Directory" },
        BlinkCmpKindReference = { link = "Special" },
        BlinkCmpKindFolder = { link = "Directory" },
        BlinkCmpKindEnumMember = { link = "Constant" },
        BlinkCmpKindConstant = { link = "Constant" },
        BlinkCmpKindStruct = { link = "Type" },
        BlinkCmpKindEvent = { link = "Type" },
        BlinkCmpKindOperator = { link = "Operator" },
        BlinkCmpKindTypeParameter = { link = "Type" },
        BlinkCmpKindCopilot = { link = "String" },

        -- IndentBlankline
        IndentBlanklineChar = { fg = theme.ui.indent_line, nocombine = true },
        IndentBlanklineSpaceChar = { fg = theme.ui.indent_line, nocombine = true },
        IndentBlanklineSpaceCharBlankline = { fg = theme.ui.indent_line, nocombine = true },
        IndentBlanklineContextChar = { fg = theme.ui.special, nocombine = true },
        IndentBlanklineContextStart = { sp = theme.ui.special, underline = true, nocombine = true },
        IblIndent = { fg = theme.ui.indent_line, nocombine = true },
        IblWhitespace = { fg = theme.ui.indent_line, nocombine = true },
        IblScope = { fg = theme.ui.special, nocombine = true },

        -- Lazy
        LazyProgressTodo = { fg = theme.ui.nontext },

        -- Trouble
        TroubleIndent = { fg = theme.ui.whitespace },
        TroublePos = { fg = theme.ui.special },

        -- Mini
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },
        MiniDiffSignAdd = { fg = theme.vcs.added, bg = theme.ui.none },
        MiniDiffSignChange = { fg = theme.vcs.changed, bg = theme.ui.none },
        MiniDiffSignDelete = { fg = theme.vcs.removed, bg = theme.ui.none },
        MiniIndentscopeSymbol = { fg = theme.syn.special1 },
        MiniIndentscopePrefix = { nocombine = true },
        MiniJump = { link = "SpellRare" },
        MiniStatuslineModeNormal = { fg = theme.ui.bg, bg = theme.statusline.normal },
        MiniStatuslineModeInsert = { fg = theme.ui.bg, bg = theme.statusline.insert },
        MiniStatuslineModeVisual = { fg = theme.ui.bg, bg = theme.statusline.visual },
        MiniStatuslineModeReplace = { fg = theme.ui.bg, bg = theme.statusline.replace },
        MiniStatuslineModeCommand = { fg = theme.ui.bg, bg = theme.statusline.command },
        MiniStatuslineModeOther = { fg = theme.ui.bg, bg = theme.statusline.other },
        MiniSurround = { link = "IncSearch" },
        MiniTrailspace = { bg = theme.vcs.removed },

        -- Snacks
        SnacksPicker = { bg = config.transparent and theme.ui.none or theme.ui.bg },
        SnacksPickerTitle = { fg = theme.ui.fg, bg = config.transparent and theme.ui.none or theme.ui.bg },
        SnacksPickerBorder = { fg = theme.ui.none, bg = theme.ui.none },
        SnacksPickerNormal = { fg = theme.ui.fg, bg = config.transparent and theme.ui.none or theme.ui.bg },
        SnacksPickerMatch = { fg = theme.ui.fg },
        SnacksPickerPrompt = { fg = theme.ui.fg },
        SnacksPickerDim = { fg = theme.ui.fg_dim },
        SnacksIndent = { fg = theme.ui.indent_line, nocombine = true },
        SnacksIndentChunk = { fg = theme.ui.special, nocombine = true },
        SnacksIndentScope = { fg = theme.ui.special, nocombine = true },
        SnacksPickerListCursorLine = { fg = theme.ui.fg, bg = theme.ui.bg_p2 },

        -- BufferLine
        BufferLineBackground = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineBuffer = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineBufferSelected = { bg = theme.ui.none, fg = theme.ui.fg },
        BufferLineBufferVisible = { fg = theme.ui.fg_dim, bg = theme.ui.none },
        BufferLineCloseButton = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineCloseButtonSelected = { fg = theme.ui.fg, bg = theme.ui.none },
        BufferLineCloseButtonVisible = { fg = theme.ui.fg_dim, bg = theme.ui.none },
        BufferLineFill = { bg = theme.ui.none },
        BufferLineIndicatorSelected = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineModified = { fg = theme.vcs.changed, bg = theme.ui.none },
        BufferLineModifiedSelected = { fg = theme.vcs.changed, bg = theme.ui.none },
        BufferLineModifiedVisible = { fg = theme.vcs.changed, bg = theme.ui.none },
        BufferLineSeparator = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineSeparatorSelected = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineSeparatorVisible = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineTab = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineTabSelected = { fg = theme.ui.fg, bg = theme.ui.none },

        -- Health
        healthError = { fg = theme.diag.error },
        healthSuccess = { fg = theme.diag.ok },
        healthWarning = { fg = theme.diag.warning },

        -- WhichKey
        WhichKey = { fg = theme.ui.fg },
        WhichKeyBorder = { fg = theme.ui.float.fg_border, bg = config.transparent and theme.ui.none or theme.ui.float.bg },
        WhichKeyDesc = { fg = theme.ui.fg_dim },
        WhichKeyFloat = { bg = config.transparent and theme.ui.none or theme.ui.float.bg },
        WhichKeyGroup = { fg = theme.syn.keyword },
        WhichKeySeparator = { fg = theme.ui.nontext },
        WhichKeyValue = { fg = theme.syn.string },

        -- Noice
        NoiceCmdline = { fg = theme.ui.fg, bg = config.transparent and theme.ui.none or theme.ui.bg },
        NoiceCmdlineIcon = { fg = theme.ui.fg_dim },
        NoiceCmdlineIconSearch = { fg = theme.ui.fg_dim },
        NoiceCmdlinePopup = { fg = theme.ui.fg, bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoiceCmdlinePopupBorder = { fg = theme.ui.float.fg_border, bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoiceCmdlinePopupTitle = { fg = theme.ui.special },
        NoiceConfirm = { bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoiceConfirmBorder = { fg = theme.ui.float.fg_border, bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoiceFormatProgressDone = { fg = theme.ui.fg, bg = theme.ui.bg_p2 },
        NoiceFormatProgressTodo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
        NoiceLspProgressClient = { fg = theme.ui.fg_dim },
        NoiceLspProgressSpinner = { fg = theme.ui.special },
        NoiceLspProgressTitle = { fg = theme.ui.fg },
        NoiceMini = { fg = theme.ui.fg, bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoicePopup = { bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoicePopupBorder = { fg = theme.ui.float.fg_border, bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoicePopupmenu = { bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoicePopupmenuBorder = { fg = theme.ui.float.fg_border, bg = config.transparent and theme.ui.none or theme.ui.bg_p1 },
        NoicePopupmenuMatch = { fg = theme.syn.fun },
        NoicePopupmenuSelected = { bg = theme.ui.bg_p2 },
        NoiceScrollbar = { bg = theme.ui.bg_p1 },
        NoiceScrollbarThumb = { bg = theme.ui.bg_p2 },
        NoiceVirtualText = { fg = theme.ui.fg_dim },

        -- Flash
        FlashBackdrop = { fg = theme.ui.fg_dim },
        FlashLabel = { fg = theme.ui.fg, bg = theme.ui.bg_search, bold = true },
        FlashMatch = { fg = theme.ui.fg, bg = theme.ui.bg_visual },
        FlashCurrent = { fg = theme.ui.fg, bg = theme.ui.bg_search },
        FlashPrompt = { link = "NormalFloat" },
        FlashPromptIcon = { fg = theme.ui.special },
        FlashCursor = { link = "Cursor" },

        -- nvim-dap
        DapBreakpoint = { fg = theme.diag.error },
        DapBreakpointCondition = { fg = theme.diag.warning },
        DapBreakpointRejected = { fg = theme.ui.fg_dim },
        DapLogPoint = { fg = theme.diag.info },
        DapStopped = { fg = theme.diag.ok },
        DapStoppedLine = { bg = theme.diff.change },

        -- nvim-dap-ui
        DapUIBreakpointsCurrentLine = { fg = theme.ui.fg, bold = true },
        DapUIBreakpointsDisabledLine = { fg = theme.ui.fg_dim },
        DapUIBreakpointsInfo = { fg = theme.diag.info },
        DapUIBreakpointsLine = { link = "DapBreakpoint" },
        DapUIBreakpointsPath = { fg = theme.ui.special },
        DapUICurrentFrameName = { link = "DapUIBreakpointsCurrentLine" },
        DapUIDecoration = { fg = theme.ui.float.fg_border },
        DapUIFloatBorder = { link = "FloatBorder" },
        DapUIFloatNormal = { link = "NormalFloat" },
        DapUILineNumber = { fg = theme.ui.special },
        DapUIModifiedValue = { fg = theme.diag.warning, bold = true },
        DapUIPlayPause = { fg = theme.diag.ok },
        DapUIRestart = { fg = theme.diag.ok },
        DapUIScope = { fg = theme.ui.special },
        DapUISource = { fg = theme.syn.string },
        DapUIStepBack = { fg = theme.diag.info },
        DapUIStepInto = { fg = theme.diag.info },
        DapUIStepOut = { fg = theme.diag.info },
        DapUIStepOver = { fg = theme.diag.info },
        DapUIStop = { fg = theme.diag.error },
        DapUIStoppedThread = { fg = theme.diag.ok },
        DapUIThread = { fg = theme.ui.fg },
        DapUIType = { link = "Type" },
        DapUIValue = { fg = theme.ui.fg_dim },
        DapUIVariable = { fg = theme.ui.fg },
        DapUIWatchesEmpty = { fg = theme.ui.fg_dim },
        DapUIWatchesError = { fg = theme.diag.error },
        DapUIWatchesValue = { fg = theme.diag.ok },

        -- Diffview
        DiffviewDiffAdd = { bg = theme.diff.add },
        DiffviewDiffChange = { bg = theme.diff.change },
        DiffviewDiffDelete = { fg = theme.ui.fg_dim, bg = theme.diff.delete },
        DiffviewDiffText = { bg = theme.diff.text },
        DiffviewDim1 = { fg = theme.ui.fg_dim },
        DiffviewFilePanelCounter = { fg = theme.ui.special },
        DiffviewFilePanelDeletions = { fg = theme.vcs.removed },
        DiffviewFilePanelFileName = { fg = theme.ui.fg },
        DiffviewFilePanelInsertions = { fg = theme.vcs.added },
        DiffviewFilePanelPath = { fg = theme.ui.fg_dim },
        DiffviewFilePanelRootPath = { fg = theme.ui.special },
        DiffviewFilePanelSelected = { fg = theme.ui.fg, bold = true },
        DiffviewFilePanelTitle = { fg = theme.ui.special, bold = true },
        DiffviewFolderName = { link = "Directory" },
        DiffviewFolderSign = { fg = theme.ui.special },
        DiffviewHash = { fg = theme.ui.fg_dim },
        DiffviewNormal = { link = "Normal" },
        DiffviewPrimary = { fg = theme.ui.special },
        DiffviewReference = { fg = theme.syn.keyword },
        DiffviewSecondary = { fg = theme.ui.fg_dim },
        DiffviewStatusAdded = { fg = theme.vcs.added },
        DiffviewStatusBroken = { fg = theme.diag.error },
        DiffviewStatusCopied = { fg = theme.diag.info },
        DiffviewStatusDeleted = { fg = theme.vcs.removed },
        DiffviewStatusIgnored = { fg = theme.ui.fg_dim },
        DiffviewStatusModified = { fg = theme.vcs.changed },
        DiffviewStatusRenamed = { fg = theme.diag.info },
        DiffviewStatusTypeChange = { fg = theme.diag.info },
        DiffviewStatusUnknown = { fg = theme.diag.error },
        DiffviewStatusUnmerged = { fg = theme.diag.warning },
        DiffviewStatusUntracked = { fg = theme.vcs.added },

        -- Alpha / Dashboard
        AlphaHeader = { fg = theme.ui.special },
        AlphaButtons = { fg = theme.ui.fg },
        AlphaShortcut = { fg = theme.syn.keyword },
        AlphaFooter = { fg = theme.ui.fg_dim },
        DashboardHeader = { fg = theme.ui.special },
        DashboardCenter = { fg = theme.ui.fg },
        DashboardShortcut = { fg = theme.syn.keyword },
        DashboardFooter = { fg = theme.ui.fg_dim },
        DashboardKey = { fg = theme.syn.keyword },
        DashboardDesc = { fg = theme.ui.fg },
        DashboardIcon = { fg = theme.ui.special },

        -- Mason
        MasonHeader = { fg = theme.ui.bg, bg = theme.syn.keyword, bold = true },
        MasonHeaderSecondary = { fg = theme.ui.bg, bg = theme.ui.special, bold = true },
        MasonHeading = { fg = theme.ui.fg, bold = true },
        MasonHighlight = { fg = theme.syn.string },
        MasonHighlightBlock = { fg = theme.ui.bg, bg = theme.syn.string },
        MasonHighlightBlockBold = { fg = theme.ui.bg, bg = theme.syn.string, bold = true },
        MasonHighlightBlockBoldSecondary = { fg = theme.ui.bg, bg = theme.ui.special, bold = true },
        MasonHighlightBlockSecondary = { fg = theme.ui.bg, bg = theme.ui.special },
        MasonHighlightSecondary = { fg = theme.ui.special },
        MasonLink = { fg = theme.syn.string, underline = true },
        MasonMuted = { fg = theme.ui.fg_dim },
        MasonMutedBlock = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
        MasonMutedBlockBold = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1, bold = true },
        MasonNormal = { link = "NormalFloat" },
        MasonWarning = { fg = theme.diag.warning },
        MasonError = { fg = theme.diag.error },

        -- Navic / Barbecue
        NavicText = { fg = theme.ui.fg_dim },
        NavicSeparator = { fg = theme.ui.nontext },
        NavicIconsFile = { link = "Directory" },
        NavicIconsModule = { link = "@module" },
        NavicIconsNamespace = { link = "@module" },
        NavicIconsPackage = { link = "@module" },
        NavicIconsClass = { link = "Type" },
        NavicIconsMethod = { link = "Function" },
        NavicIconsProperty = { link = "@property" },
        NavicIconsField = { link = "@variable.member" },
        NavicIconsConstructor = { link = "@constructor" },
        NavicIconsEnum = { link = "Type" },
        NavicIconsInterface = { link = "Type" },
        NavicIconsFunction = { link = "Function" },
        NavicIconsVariable = { fg = theme.ui.fg_dim },
        NavicIconsConstant = { link = "Constant" },
        NavicIconsString = { link = "String" },
        NavicIconsNumber = { link = "Number" },
        NavicIconsBoolean = { link = "Boolean" },
        NavicIconsArray = { link = "Type" },
        NavicIconsObject = { link = "Type" },
        NavicIconsKey = { link = "Keyword" },
        NavicIconsNull = { link = "Constant" },
        NavicIconsEnumMember = { link = "Constant" },
        NavicIconsStruct = { link = "Type" },
        NavicIconsEvent = { link = "Type" },
        NavicIconsOperator = { link = "Operator" },
        NavicIconsTypeParameter = { link = "Type" },

        -- Barbecue
        BarbecueSeparator = { fg = theme.ui.nontext },
        BarbecueModified = { fg = theme.vcs.changed },
        BarbecueDirname = { fg = theme.ui.fg_dim },
        BarbecueBasename = { fg = theme.ui.fg },
        BarbecueContext = { fg = theme.ui.fg_dim },
    }
end

return M
