local M = {}

---@param colors table
---@param config? table
function M.setup(colors, config)
    config = config or require("zen").config
    local theme = colors.theme

    return {
        -- Gitsigns
        GitSignsAdd = { fg = theme.vcs.added, bg = theme.ui.none },
        GitSignsChange = { fg = theme.vcs.changed, bg = theme.ui.none },
        GitSignsDelete = { fg = theme.vcs.removed, bg = theme.ui.none },
        GitSignsChangedelete = { fg = theme.vcs.removed, bg = theme.ui.none },
        GitSignsTopdelete = { fg = theme.vcs.removed, bg = theme.ui.none },

        -- Neogit
        NeogitDiffContextHighlight = { bg = theme.diff.change },
        NeogitHunkHeader = { fg = theme.syn.fun },
        NeogitHunkHeaderHighlight = { fg = theme.syn.constant, bg = theme.diff.change },
        NeogitDiffAddHighlight = { bg = theme.diff.add },
        NeogitDiffDeleteHighlight = { bg = theme.diff.delete },

        -- TreeSitter Context
        TreesitterContext = { link = "Folded" },
        TreesitterContextLineNumber = { fg = theme.ui.special, bg = theme.ui.none },

        -- Telescope
        TelescopeBorder = { fg = theme.ui.float.fg_border, bg = config.transparent and theme.ui.none or theme.ui.bg },
        TelescopeTitle = { fg = theme.ui.special },
        TelescopeSelection = { link = "CursorLine" },
        TelescopeSelectionCaret = { link = "CursorLineNr" },
        TelescopeResultsClass = { link = "Structure" },
        TelescopeResultsStruct = { link = "Structure" },
        TelescopeResultsField = { link = "@field" },
        TelescopeResultsMethod = { link = "Function" },
        TelescopeResultsVariable = { link = "@variable" },

        -- NvimTree
        NvimTreeNormal = { link = "Normal" },
        NvimTreeNormalNC = { link = "NvimTreeNormal" },
        NvimTreeRootFolder = { fg = theme.syn.identifier },
        NvimTreeGitDirty = { fg = theme.vcs.changed },
        NvimTreeGitNew = { fg = theme.vcs.added },
        NvimTreeGitDeleted = { fg = theme.vcs.removed },
        NvimTreeGitStaged = { fg = theme.vcs.added },
        NvimTreeSpecialFile = { fg = theme.syn.special1 },
        NvimTreeImageFile = { fg = theme.syn.special2 },
        NvimTreeSymlink = { link = "Type" },
        NvimTreeFolderName = { link = "Directory" },
        NvimTreeExecFile = { fg = theme.syn.string },
        NvimTreeOpenedFile = { fg = theme.syn.special1, italic = true },
        NvimTreeWinSeparator = { link = "WinSeparator" },

        -- NeoTree
        NeoTreeNormal = { link = "Normal" },
        NeoTreeNormalNC = { link = "Normal" },
        NeoTreeRootName = { fg = theme.syn.identifier },
        NeoTreeModified = { link = "String" },
        NeoTreeTitleBar = { link = "Title" },
        NeoTreeDimText = { fg = theme.ui.fg_dim },
        NeoTreeGitModified = { fg = theme.vcs.changed },
        NeoTreeGitAdded = { fg = theme.vcs.added },
        NeoTreeGitDeleted = { fg = theme.vcs.removed },
        NeoTreeGitStaged = { fg = theme.vcs.added },
        NeoTreeGitConflict = { fg = theme.diag.error },
        NeoTreeIndentMarker = { link = "NonText" },

        -- Notify
        NotifyBackground = { bg = config.transparent and theme.ui.none or theme.ui.bg },
        NotifyERRORBorder = { link = "DiagnosticError" },
        NotifyWARNBorder = { link = "DiagnosticWarn" },
        NotifyINFOBorder = { link = "DiagnosticInfo" },
        NotifyHINTBorder = { link = "DiagnosticHint" },
        NotifyDEBUGBorder = { link = "Debug" },
        NotifyTRACEBorder = { link = "Comment" },
        NotifyERRORIcon = { link = "DiagnosticError" },
        NotifyWARNIcon = { link = "DiagnosticWarn" },
        NotifyINFOIcon = { link = "DiagnosticInfo" },
        NotifyHINTIcon = { link = "DiagnosticHint" },
        NotifyDEBUGIcon = { link = "Debug" },
        NotifyTRACEIcon = { link = "Comment" },
        NotifyERRORTitle = { link = "DiagnosticError" },
        NotifyWARNTitle = { link = "DiagnosticWarn" },
        NotifyINFOTitle = { link = "DiagnosticInfo" },
        NotifyHINTTitle = { link = "DiagnosticHint" },
        NotifyDEBUGTitle = { link = "Debug" },
        NotifyTRACETitle = { link = "Comment" },

        -- nvim-cmp
        CmpDocumentation = { link = "NormalFloat" },
        CmpDocumentationBorder = { link = "FloatBorder" },
        CmpCompletion = { link = "Pmenu" },
        CmpCompletionSel = { link = "PmenuSel" },
        CmpCompletionBorder = { fg = theme.ui.bg_search, bg = theme.ui.pmenu.bg },
        CmpCompletionThumb = { link = "PmenuThumb" },
        CmpCompletionSbar = { link = "PmenuSbar" },
        CmpItemAbbr = { fg = theme.ui.pmenu.fg },
        CmpItemAbbrDeprecated = { fg = theme.syn.comment, strikethrough = true },
        CmpItemAbbrMatch = { fg = theme.syn.fun },
        CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
        CmpItemKindDefault = { fg = theme.ui.fg_dim },
        CmpItemMenu = { fg = theme.ui.fg_dim },
        CmpGhostText = { fg = theme.syn.comment },

        CmpItemKindText = { fg = theme.ui.fg },
        CmpItemKindMethod = { link = "@function.method" },
        CmpItemKindFunction = { link = "Function" },
        CmpItemKindConstructor = { link = "@constructor" },
        CmpItemKindField = { link = "@variable.member" },
        CmpItemKindVariable = { fg = theme.ui.fg_dim },
        CmpItemKindClass = { link = "Type" },
        CmpItemKindInterface = { link = "Type" },
        CmpItemKindModule = { link = "@module" },
        CmpItemKindProperty = { link = "@property" },
        CmpItemKindUnit = { link = "Number" },
        CmpItemKindValue = { link = "String" },
        CmpItemKindEnum = { link = "Type" },
        CmpItemKindKeyword = { link = "Keyword" },
        CmpItemKindSnippet = { link = "Special" },
        CmpItemKindColor = { link = "Special" },
        CmpItemKindFile = { link = "Directory" },
        CmpItemKindReference = { link = "Special" },
        CmpItemKindFolder = { link = "Directory" },
        CmpItemKindEnumMember = { link = "Constant" },
        CmpItemKindConstant = { link = "Constant" },
        CmpItemKindStruct = { link = "Type" },
        CmpItemKindEvent = { link = "Type" },
        CmpItemKindOperator = { link = "Operator" },
        CmpItemKindTypeParameter = { link = "Type" },
        CmpItemKindCopilot = { link = "String" },

        -- blink.cmp
        BlinkCmpMenu = { link = "Pmenu" },
        BlinkCmpMenuSelection = { link = "PmenuSel" },
        BlinkCmpMenuBorder = { fg = theme.ui.bg_search, bg = config.transparent and theme.ui.none or theme.ui.pmenu.bg },
        BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
        BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
        BlinkCmpLabel = { fg = theme.ui.pmenu.fg },
        BlinkCmpLabelMatch = { fg = theme.syn.fun },
        BlinkCmpLabelDetails = { fg = theme.syn.comment },
        BlinkCmpLabelDeprecated = { fg = theme.syn.comment, strikethrough = true },
        BlinkCmpGhostText = { fg = theme.syn.comment },
        BlinkCmpDoc = { link = "NormalFloat" },
        BlinkCmpDocBorder = { link = "FloatBorder" },
        BlinkCmpDocCursorLine = { link = "Visual" },
        BlinkCmpSignatureHelp = { link = "NormalFloat" },
        BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
        BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },

        BlinkCmpKind = { fg = theme.ui.fg_dim },
        BlinkCmpKindText = { fg = theme.ui.fg },
        BlinkCmpKindMethod = { link = "@function.method" },
        BlinkCmpKindFunction = { link = "Function" },
        BlinkCmpKindConstructor = { link = "@constructor" },
        BlinkCmpKindField = { link = "@variable.member" },
        BlinkCmpKindVariable = { fg = theme.ui.fg_dim },
        BlinkCmpKindClass = { link = "Type" },
        BlinkCmpKindInterface = { link = "Type" },
        BlinkCmpKindModule = { link = "@module" },
        BlinkCmpKindProperty = { link = "@property" },
        BlinkCmpKindUnit = { link = "Number" },
        BlinkCmpKindValue = { link = "String" },
        BlinkCmpKindEnum = { link = "Type" },
        BlinkCmpKindKeyword = { link = "Keyword" },
        BlinkCmpKindSnippet = { link = "Special" },
        BlinkCmpKindColor = { link = "Special" },
        BlinkCmpKindFile = { link = "Directory" },
        BlinkCmpKindReference = { link = "Special" },
        BlinkCmpKindFolder = { link = "Directory" },
        BlinkCmpKindEnumMember = { link = "Constant" },
        BlinkCmpKindConstant = { link = "Constant" },
        BlinkCmpKindStruct = { link = "Type" },
        BlinkCmpKindEvent = { link = "Type" },
        BlinkCmpKindOperator = { link = "Operator" },
        BlinkCmpKindTypeParameter = { link = "Type" },
        BlinkCmpKindCopilot = { link = "String" },

        -- IndentBlankline
        IndentBlanklineChar = { fg = theme.ui.indent_line, nocombine = true },
        IndentBlanklineSpaceChar = { fg = theme.ui.indent_line, nocombine = true },
        IndentBlanklineSpaceCharBlankline = { fg = theme.ui.indent_line, nocombine = true },
        IndentBlanklineContextChar = { fg = theme.ui.special, nocombine = true },
        IndentBlanklineContextStart = { sp = theme.ui.special, underline = true, nocombine = true },
        IblIndent = { fg = theme.ui.indent_line, nocombine = true },
        IblWhitespace = { fg = theme.ui.indent_line, nocombine = true },
        IblScope = { fg = theme.ui.special, nocombine = true },

        -- Lazy
        LazyProgressTodo = { fg = theme.ui.nontext },

        -- Trouble
        TroubleIndent = { fg = theme.ui.whitespace },
        TroublePos = { fg = theme.ui.special },

        -- Mini
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },
        MiniDiffSignAdd = { fg = theme.vcs.added, bg = theme.ui.none },
        MiniDiffSignChange = { fg = theme.vcs.changed, bg = theme.ui.none },
        MiniDiffSignDelete = { fg = theme.vcs.removed, bg = theme.ui.none },
        MiniIndentscopeSymbol = { fg = theme.syn.special1 },
        MiniIndentscopePrefix = { nocombine = true },
        MiniJump = { link = "SpellRare" },
        MiniStatuslineModeNormal = { fg = theme.ui.bg, bg = theme.statusline.normal },
        MiniStatuslineModeInsert = { fg = theme.ui.bg, bg = theme.statusline.insert },
        MiniStatuslineModeVisual = { fg = theme.ui.bg, bg = theme.statusline.visual },
        MiniStatuslineModeReplace = { fg = theme.ui.bg, bg = theme.statusline.replace },
        MiniStatuslineModeCommand = { fg = theme.ui.bg, bg = theme.statusline.command },
        MiniStatuslineModeOther = { fg = theme.ui.bg, bg = theme.statusline.other },
        MiniSurround = { link = "IncSearch" },
        MiniTrailspace = { bg = theme.vcs.removed },

        -- Snacks
        SnacksPicker = { bg = config.transparent and theme.ui.none or theme.ui.bg },
        SnacksPickerTitle = { fg = theme.ui.fg, bg = config.transparent and theme.ui.none or theme.ui.bg },
        SnacksPickerBorder = { fg = theme.ui.none, bg = theme.ui.none },
        SnacksPickerNormal = { fg = theme.ui.fg, bg = config.transparent and theme.ui.none or theme.ui.bg },
        SnacksPickerMatch = { fg = theme.ui.fg },
        SnacksPickerPrompt = { fg = theme.ui.fg },
        SnacksPickerDim = { fg = theme.ui.fg_dim },
        SnacksIndent = { fg = theme.ui.indent_line, nocombine = true },
        SnacksIndentChunk = { fg = theme.ui.special, nocombine = true },
        SnacksIndentScope = { fg = theme.ui.special, nocombine = true },
        SnacksPickerListCursorLine = { fg = theme.ui.fg, bg = theme.ui.bg_p2 },

        -- BufferLine
        BufferLineBackground = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineBuffer = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineBufferSelected = { bg = theme.ui.none, fg = theme.ui.fg },
        BufferLineBufferVisible = { fg = theme.ui.fg_dim, bg = theme.ui.none },
        BufferLineCloseButton = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineCloseButtonSelected = { fg = theme.ui.fg, bg = theme.ui.none },
        BufferLineCloseButtonVisible = { fg = theme.ui.fg_dim, bg = theme.ui.none },
        BufferLineFill = { bg = theme.ui.none },
        BufferLineIndicatorSelected = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineModified = { fg = theme.vcs.changed, bg = theme.ui.none },
        BufferLineModifiedSelected = { fg = theme.vcs.changed, bg = theme.ui.none },
        BufferLineModifiedVisible = { fg = theme.vcs.changed, bg = theme.ui.none },
        BufferLineSeparator = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineSeparatorSelected = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineSeparatorVisible = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineTab = { fg = theme.ui.special, bg = theme.ui.none },
        BufferLineTabSelected = { fg = theme.ui.fg, bg = theme.ui.none },

        -- Health
        healthError = { fg = theme.diag.error },
        healthSuccess = { fg = theme.diag.ok },
        healthWarning = { fg = theme.diag.warning },
    }
end

return M
